FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY wire .

COPY . .

RUN chmod +x ./wire

RUN GOFLAGS="-mod=vendor" ./wire ./internal/injector

RUN CGO_ENABLED=0 GOOS=linux go build -mod=vendor -o main ./cmd/main.go


FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/main .

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

ENV PORT=8383
ENV GIN_MODE=release

EXPOSE 8383

CMD ["./main"]