FROM new-nexus.bri.co.id/library/golang:1.24.3-alpine AS builder

WORKDIR /app

COPY wire .

COPY . .

RUN chmod +x ./wire

RUN GOFLAGS="-mod=vendor" ./wire ./internal/injector

RUN CGO_ENABLED=0 GOOS=linux go build -mod=vendor -o main ./cmd/main.go


FROM new-nexus.bri.co.id/library/alpine:latest

# Catatan: Jika perintah apk di bawah gagal karena firewall,
# sebaiknya gunakan base image yang sudah di-install ca-certificates & tzdata sebelumnya.
# RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

COPY --from=builder /app/main .

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

ENV PORT=8383
ENV GIN_MODE=release

EXPOSE 8383

CMD ["./main"]